aplication_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AplicationBundle:Default:index }


activity_log:
    pattern:  /activity_log/{userId}
    defaults: { _controller: AplicationBundle:ActivityLog:index }

settings_update:
    pattern:  /settings
    defaults: { _controller: AplicationBundle:Settings:settings }
