parameters:
#    aplication.example.class: Admin\AplicationBundle\Example

services:
#    aplication.example:
#        class: %aplication.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
