post:
    pattern:  /list
    defaults: { _controller: "ArticleBundle:Post:index" }

post_show:
    pattern:  /{id}/show
    defaults: { _controller: "ArticleBundle:Post:show" }

post_new:
    pattern:  /new
    defaults: { _controller: "ArticleBundle:Post:new" }

post_create:
    pattern:  /create
    defaults: { _controller: "ArticleBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    pattern:  /{id}/edit/{locale}
    defaults: { _controller: ArticleBundle:Post:edit, locale: %locale% }

post_update:
    pattern:  /{id}/update/{locale}
    defaults: { _controller: "ArticleBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ArticleBundle:Post:delete" }
    requirements: { _method: post|delete }

post_latest:
    pattern:  /latest/{num}
    defaults: { _controller: "ArticleBundle:Post:getLatest" }