article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

yoda_nav_menu:
    resource: "@NavMenuBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation
    
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"