article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /admin/

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /admin/

yoda_nav_menu:
    resource: "@NavMenuBundle/Resources/config/routing.yml"
    prefix:   /admin/

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /admin/

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation
    
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

category:
        resource: "@CategoryBundle/Resources/config/routing.yml"
        prefix:   /admin/
