security:
    encoders:
        ADmin\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_users:
            entity: { class: UserBundle:User  }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/category/, roles: ROLE_USER }
        - { path: ^/admin/user/, roles: ROLE_USER }
        - { path: ^/admin/page/, roles: ROLE_USER }
        - { path: ^/admin/post/, roles: ROLE_USER }
        - { path: ^/admin/dashboard/, roles: ROLE_USER }
        - { path: ^/admin/navmenu/, roles: ROLE_USER }
#        - { path: ^/admin/event/create , roles: ROLE_SUPER_ADMIN }
#        - { path: ^/efconnect, role: ROLE_USER }
#        - { path: ^/elfinder, role: ROLE_USER }
