<?php

namespace Admin\NavMenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavMenuRepository extends EntityRepository
{
    public function findAllNMenu()
    {
        return $this->createQueryBuilder('u')
            ->addOrderBy('u.parentId ')
            ->addOrderBy('u.sort ')    
            ->getQuery()
            ->getResult()
        ;
    }
    
    
    public function getTree( array $elements ) {
      
        return $this->_buildTree($elements);
        
    }
    
    
    private function _buildTree( array $elements, $parentId = 0 ){
        
        $branch = array();
        
        foreach ($elements as $element) { 
            
            $elParentId = $element->getParentId(); 

            if ($elParentId == $parentId) {

               $elId = $element->getId();

               $children = $this->_buildTree($elements, $elId);                   

               if ($children) {
                   
                   $element->setChildren($children);
                   
               }

               $branch[] = $element;
            }
        }
        
        return  $branch;
        
    }
    
}
