Admin\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: username, message: This username is already taken}

    properties:
        username:
            - NotBlank: { message: You must provide a username}