front_hello:
    pattern:  /
    defaults: { _controller: FrontBundle:Default:index }


front_page:
    pattern:  /page/{page}
    defaults: { _controller: FrontBundle:Default:page }
    
front_post:
    pattern:  /post/{post}
    defaults: { _controller: FrontBundle:Default:post }
front_navigation:
    pattern:  /navigation/{position}
    defaults: { _controller: FrontBundle:Default:navigation, position:top }
