#front_hello:
#    pattern:  /
#    defaults: { _controller: FrontBundle:Default:index}
front_hello:
    pattern:  /{locale}
    defaults: { _controller: FrontBundle:Default:index, locale: %locale%}
    requirements:
        locale:  en|sr|cir

front_page:
    pattern:  /page/{page}/{locale}
    defaults: { _controller: FrontBundle:Default:page, locale: %locale% }
    
front_post:
    pattern:  /post/{post}/{locale}
    defaults: { _controller: FrontBundle:Default:post, locale: %locale% }
front_navigation:
    pattern:  /navigation/{position}/{locale}
    defaults: { _controller: FrontBundle:Default:navigation, position:top | locale:%locale% }
