parameters:
#    front.example.class: Site\FrontBundle\Example
services:
    site.twig.site_twig_extension:
        class: Site\FrontBundle\Twig\Extensions\SiteTwigExtensions
        tags:
            - { name: twig.extension }
