parameters:
#    admin_nav_menu.example.class: Admin\NavMenuBundle\Example

services:
#    admin_nav_menu.example:
#        class: %admin_nav_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
