page:
    pattern:  /list
    defaults: { _controller: "PageBundle:Page:index" }

page_show:
    pattern:  /{id}/show
    defaults: { _controller: "PageBundle:Page:show" }

page_new:
    pattern:  /new
    defaults: { _controller: "PageBundle:Page:new" }

page_create:
    pattern:  /create
    defaults: { _controller: "PageBundle:Page:create" }
    requirements: { _method: post }

page_edit:
    pattern:  /edit/{id}/{locale}
    defaults: { _controller: PageBundle:Page:edit, locale: %locale% }

page_update:
    pattern:  /update/{id}/{locale}
    defaults: { _controller: "PageBundle:Page:update" }
    requirements: { _method: post|put }

page_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PageBundle:Page:delete" }
    requirements: { _method: post|delete }

page_latest:
    pattern:  /latest/{num}
    defaults: { _controller: "PageBundle:Page:getLatestPages" }

pages_tree_select:
    pattern:  /tree_select/{form}/{input}
    defaults: { _controller: "PageBundle:Page:getPagesTree" }


