navmenu:
    pattern:  /{position}
    defaults: { _controller: "NavMenuBundle:NavMenu:index", position: top}
    requirements:
            name: ".+"

navmenu_show:
    pattern:  /{id}/show
    defaults: { _controller: "NavMenuBundle:NavMenu:show" }

navmenu_new:
    pattern:  /new/{position}
    defaults: { _controller: "NavMenuBundle:NavMenu:new", position: top }

navmenu_create:
    pattern:  /create/navigation
    defaults: { _controller: "NavMenuBundle:NavMenu:create" }
    requirements: { _method: post }

navmenu_edit:
    pattern:  /{id}/edit/{position}/{locale}
    defaults: { _controller: "NavMenuBundle:NavMenu:edit", locale: %locale% }

navmenu_update:
    pattern:  /{id}/update/{position}/{locale}
    defaults: { _controller: "NavMenuBundle:NavMenu:update", locale: %locale% }
    requirements: { _method: post|put }

navmenu_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NavMenuBundle:NavMenu:delete" }
    requirements: { _method: post|delete }

navmenu_arange:
    pattern:  /arange/{position}
    defaults: { _controller: "NavMenuBundle:NavMenu:arange"  }
