Admin\NavMenuBundle\Entity\NavMenu:
    type: entity
    table: null
    repositoryClass: Admin\NavMenuBundle\Entity\NavMenuRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        url:
            type: string
            length: 255
        pageId:
            type: integer
            column: page_id
        name:
            type: string
            length: 255
        parentId:
            type: integer
            column: parent_id
        sort:
            type: integer
    lifecycleCallbacks: {  }
